name: uitars-vllm
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - nvidia
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - dbus=1.16.2=h24cb091_1
  - dbus-python=1.3.2=py310h561bdf3_6
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgirepository=1.84.0=hac26d07_4
  - libglib=2.86.2=h6548e54_1
  - libgomp=15.2.0=he0feb66_14
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.53=h421ea60_0
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libuuid=2.41.2=he9a06e4_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycairo=1.29.0=py310h8c3e0f7_0
  - pygobject=3.54.5=py310h36b64b3_2
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - zstd=1.5.7=h3691f8a_5
  - pip:
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - anthropic==0.71.0
      - apache-tvm-ffi==0.1.4
      - astor==0.8.1
      - async-timeout==5.0.1
      - av==16.0.1
      - blake3==1.0.8
      - brotli==1.2.0
      - cachetools==6.2.2
      - cbor2==5.7.1
      - certifi==2025.11.12
      - click==8.2.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.12.2
      - contourpy==1.3.2
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.123.5
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.5.2
      - fastar==0.8.0
      - fastrlock==0.8.3
      - ffmpy==1.0.0
      - filelock==3.19.1
      - flashinfer-python==0.5.3
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - fuzzywuzzy==0.18.0
      - gguf==0.17.1
      - gradio==6.0.2
      - gradio-client==2.0.1
      - groovy==0.1.2
      - hf-xet==1.2.0
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - interegular==0.3.3
      - jmespath==1.0.1
      - json5==0.12.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - levenshtein==0.27.3
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - model-hosting-container-standards==0.1.9
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - networkx==3.3
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.8.1
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.5
      - outlines-core==0.2.11
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - pillow==11.3.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - python-levenshtein==0.27.3
      - pytz==2025.2
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - rapidfuzz==3.14.3
      - ray==2.52.1
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.46.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - starlette==0.50.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.5.0
      - typer==0.20.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.12.0
      - watchfiles==1.1.1
      - websockets==15.0.1
      - werkzeug==3.1.4
      - xgrammar==0.1.27
      - yarl==1.22.0
prefix: /data0/miniconda3/envs/uitars-vllm
